const CHESS_API_GM_LIST = process.env.NEXT_PUBLIC_CHESS_API_GM_LIST;
const CHESS_API_PLAYER = process.env.NEXT_PUBLIC_CHESS_API_PLAYER;

export const API_CONSTANTS = {
  CHESS_API_GM_LIST: CHESS_API_GM_LIST ?? "",
  CHESS_API_PLAYER: CHESS_API_PLAYER ?? "",
};
